# Generated by Django 5.0.7 on 2024-07-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_rename_total_amount_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_paid',
            new_name='total_amount',
        ),
    ]
