# Generated by Django 5.0.7 on 2024-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_remove_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
